import { jsPDF } from 'jspdf';

export const downloadReport = (analysis) => {
  const doc = new jsPDF();

  // Title
  doc.setFontSize(22);
  doc.setTextColor(37, 99, 235);
  doc.text('AI Resume Analysis Report', 20, 20);

  // Date
  doc.setFontSize(10);
  doc.setTextColor(100);
  doc.text(`Generated: ${new Date().toLocaleString()}`, 20, 30);

  // ATS Score
  doc.setFontSize(18);
  doc.setTextColor(0);
  doc.text(`ATS Score: ${Math.round(Number(analysis.atsScore) * 100)}%`, 20, 50);

  // Matched Skills
  doc.setFontSize(16);
  doc.setTextColor(16, 185, 129);
  doc.text('Matched Skills', 20, 70);
  doc.setFontSize(12);
  doc.setTextColor(0);
  analysis.matchedSkills?.forEach((skill, index) => {
    doc.text(`• ${skill}`, 25, 80 + index * 8);
  });

  // Missing Skills
  const missingStart = 90 + (analysis.matchedSkills?.length || 0) * 8;
  doc.setFontSize(16);
  doc.setTextColor(239, 68, 68);
  doc.text('Missing Skills', 20, missingStart);
  doc.setFontSize(12);
  doc.setTextColor(0);
  analysis.missingSkills?.forEach((skill, index) => {
    doc.text(`• ${skill}`, 25, missingStart + 10 + index * 8);
  });

  // Suggestions
  const suggestionStart = missingStart + 20 + (analysis.missingSkills?.length || 0) * 8;
  doc.setFontSize(16);
  doc.setTextColor(37, 99, 235);
  doc.text('AI Suggestions', 20, suggestionStart);
  doc.setFontSize(12);
  doc.setTextColor(0);
  analysis.suggestions?.forEach((s, index) => {
    const lines = doc.splitTextToSize(`• ${s}`, 170);
    doc.text(lines, 25, suggestionStart + 10 + index * 12);
  });

  // Footer
  doc.setFontSize(10);
  doc.setTextColor(120);
  doc.text('Generated by AI Resume Analyzer', 20, 285);

  doc.save('AI_Resume_Report.pdf');
};